version: '3.7'

volumes:
  mysql_data:
  vault-transit:

networks:
  defaultnet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: freepbxint
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

secrets:
  mysql_root_password:
    file: mysql_root_password.txt

services:
  db:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      defaultnet:
        ipv4_address: 172.18.0.10

  vault-transit:
    restart: always
    image: vault-transit:custom
    environment:
      VAULT_ADDR: http://127.0.0.1:8200 
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-transit:/vault
    networks:
      - defaultnet
    ports:
      - "8200:8200/tcp"