version: '3.7'

volumes:
  mysql_data:
  var_log:
  var_mail:
  var_opt:
  var_spool:
  var_www:
  var_local:
  var_lib:
  var_backups:
  etc_data:
  usr_data:
  asterisk_home:
  vault_logs:
  vault_backend:
  vault_config:

networks:
  defaultnet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: freepbxint
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

secrets:
   mysql_root_password:
     file: mysql_root_password.txt
   freepbxuser_password:
     file: freepbxuser_password.txt

services:
  db:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER: freepbxuser
      MYSQL_PASSWORD_FILE: /run/secrets/freepbxuser_password
    secrets:
       - mysql_root_password
       - freepbxuser_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - defaultnet

  freepbx:
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
      MYSQL_PASSWORD: /run/secrets/freepbxuser_password
    cap_add:
      - NET_ADMIN
    secrets:
       - mysql_root_password
       - freepbxuser_password
    volumes:
      - .:/usr/src
      - var_log:/var/log
      - var_mail:/var/mail
      - var_opt:/var/opt
      - var_spool:/var/spool
      - var_www:/var/www
      - var_local:/var/local
      - var_lib:/var/lib
      - var_backups:/var/backups
      - etc_data:/etc
      - usr_data:/usr
      - asterisk_home:/home/asterisk
    networks:
      - defaultnet
    ports:
      # If you aren't using a reverse proxy
      - "80:80/tcp"
      # If you want SSL Support and not using a reverse proxy
      # - "443:443/tcp"
      - "5038:5038/tcp"
      - "8001:8001/tcp"
      - "8003:8003/tcp"
      - "4569:4569/udp"
      - "5060:5060/udp"
      - "5061:5061/udp"
      - "5160:5160/udp"
      - "5161:5161/udp"
    depends_on:
      - db

  vault:
    restart: always
    build: vault/
    #image: hashicorp/vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ENABLE_FILE_PERMISSIONS_CHECK: true
    volumes:
      - vault_logs:/vault/log
      - vault_backend:/vault/file
      - vault_config:/etc/vault:ro
    networks:
      - defaultnet
    ports:
      - "8200:8200/tcp"
      - "8201:8201/tcp"
    depends_on:
      - db
      - freepbx