version: '3.7'

services:
  db:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      #MYSQL_DATABASE: asterisk
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf 
    ports:
    - target: 3306
      published: 3306
      protocol: tcp

  freepbx:
    build: .
    #command: /usr/src/freepbx/start_asterisk start && /usr/src/freepbx/install -n --dbhost=db
    volumes:
      - .:/usr/src
    ports:
    - target: 80
      published: 8080
      protocol: tcp
    depends_on:
      - db

volumes:
  mysql_data: