version: '3.2'

services:
  db:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf 
    ports:
    - target: 3306
      published: 3306
      protocol: tcp

  freepbx:
    build: .
    #command: /bin/bash -c /usr/src/freepbx/start_asterisk start
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
      - db

volumes:
  mysql_data:
