version: '3.7'

volumes:
  mysql_data:
  vault-transit:
  var_data:
  usr_data:
  etc_data:
  asterisk_home:

networks:
  defaultnet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: freepbxint
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

secrets:
  mysql_root_password:
    file: mysql_root_password.txt
  freepbxuser_password:
    file: freepbxuser_password.txt

services:
  db:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER: freepbxuser
      MYSQL_PASSWORD_FILE: /run/secrets/freepbxuser_password
    secrets:
      - mysql_root_password
      - freepbxuser_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      defaultnet:
        ipv4_address: 172.18.0.10

  freepbx:
    #image: escomputers/freepbx:latest
    image: freepbx:custom
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
      MYSQL_PASSWORD: /run/secrets/freepbxuser_password
    cap_add:
      - NET_ADMIN
    secrets:
       - mysql_root_password
       - freepbxuser_password
    volumes:
      - .:/usr/src
      - var_data:/var
      - etc_data:/etc
      - usr_data:/usr
      - asterisk_home:/home/asterisk
    networks:
      defaultnet:
        ipv4_address: 172.18.0.20
    ports:
      # If you aren't using a reverse proxy
      - "80:80/tcp"
      # If you want SSL Support and not using a reverse proxy
      # - "443:443/tcp"
      - "5038:5038/tcp"
      - "8001:8001/tcp"
      - "8003:8003/tcp"
      - "4569:4569/udp"
      - "5060:5060/udp"
      - "5061:5061/udp"
      - "5160:5160/udp"
      - "5161:5161/udp"
    depends_on:
      - db